packages:
  - 'plugins/*'
  - 'packages/*'

catalogs:
  deps:
    # typescript-eslint ecosystem (keep versions aligned)
    '@typescript-eslint/utils': '^8.62.0'

  dev:
    # typescript-eslint ecosystem (keep versions aligned)
    '@typescript-eslint/rule-tester': '8.62.1'
    typescript-eslint: '8.62.1'

    # build & test toolchain
    tsdown: '0.22.3'
    # keep `@vitest/coverage-v8` aligned with `vitest`
    '@vitest/coverage-v8': '4.1.9'
    vitest: '4.1.9'

    # plugin dev utilities
    '@marcalexiei/prettier-config': '2.0.0'
    dedent: '1.7.2'
    eslint-doc-generator: '3.7.0'
    prettier: '3.9.4'

allowBuilds:
  unrs-resolver: true

trustPolicy: no-downgrade
minimumReleaseAge: 1440
minimumReleaseAgeExclude:
  - js-yaml@3.15.0

dedupePeers: true
dedupePeerDependents: true
