name: 📝 Other
description: Use this when none of the other types apply
title: Fill with relevant title

body:
  - type: markdown
    attributes:
      value: |
        Please fill out the details below. The more information you give, the easier it is to understand the issue and help you.

  - type: textarea
    id: description
    attributes:
      label: 🧩 Description
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: ✒️ Additional context
      description: |
        Add any other relevant context info.
    validations:
      required: false
